version: '2'

volumes:
  redis:
    driver: local

  postgresql:
    driver: local

  redmine:
    driver: local

  gitlab:
    driver: local

services:
  redis:
    restart: always
    image: sameersbn/redis:latest
    command:
      - --loglevel warning
    volumes:
      - redis:/var/lib/redis


  postgresql:
    restart: always
    image: sameersbn/postgresql:9.6-2
    environment:
      # - DB_USER=rdmn
      # - DB_PASS=dIa84!j.g
      # - DB_NAME=redmine
      - DB_USER=gtlb
      - DB_PASS=t/41f.1j8-1
      - DB_NAME=gitlab
    volumes:
      - postgresql:/var/lib/postgresql

  redmine:
    restart: always
    image: sameersbn/redmine:3.3.2-1
    environment:
      - TZ=America/Bogota

      - DB_USER=rdmn
      - DB_PASS=dIa84!j.g
      - DB_NAME=redmine

      - REDMINE_HTTPS=true
      - REDMINE_SECRET_TOKEN=jk1usfkj19sfn1r094tkl56ags

      - REDMINE_CONCURRENT_UPLOADS=2

      - REDMINE_BACKUP_SCHEDULE=daily
      - REDMINE_BACKUP_EXPIRY=604800

      - SMTP_HOST=mail.privateemail.com
      - SMTP_USER=system@mllcrtv.me
      - SMTP_PASS=mllcrtvsystem
    volumes:
      - redmine:/home/redmine/data

  gitlab:
    restart: always
    image: sameersbn/gitlab:9.0.5
    environment:
      - DB_USER=gtlb
      - DB_PASS=t/41f.1j8-1
      - DB_NAME=gitlab

      - TZ=America/Bogota
      - GITLAB_TIMEZONE=Bogota

      - GITLAB_HTTPS=true

      - GITLAB_HOST=git.mllcrtv.me
      - GITLAB_PORT=443
      - GITLAB_SSH_PORT=10022
      - GITLAB_SECRETS_DB_KEY_BASE=jd92kg92mdgi2emrdwgi2ermdi2efmwdi2efjdwfi2ef
      - GITLAB_SECRETS_SECRET_KEY_BASE=mfdi2efifi2efi2gwd92efmf9dwi2efidf92efm9
      - GITLAB_SECRETS_OTP_KEY_BASE=sfi12wfdfmg9j9hhuyhsd2efinu8dnf280j307234ni

      - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true

      - GITLAB_EMAIL=system@mllcrtv.me
      - GITLAB_EMAIL_REPLY_TO=system@mllcrtv.me
      - GITLAB_INCOMING_EMAIL_ADDRESS=system@mllcrtv.me

      - GITLAB_BACKUP_SCHEDULE=daily
      - GITLAB_BACKUP_EXPIRY=604800

      - SMTP_HOST=mail.privateemail.com
      - SMTP_USER=system@mllcrtv.me
      - SMTP_PASS=mllcrtvsystem

      - IMAP_ENABLED=true
      - IMAP_HOST=mail.privateemail.com
    ports:
      - "10022:22"
    volumes:
      - gitlab:/home/git/data

  nginx:
    restart: always
    image: sameersbn/nginx:1.10.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./certs:/certs
