version: '2'

volumes:
  redis:
    driver: local

  postgresql:
    driver: local

  redmine:
    driver: local

  gitlab:
    driver: local

  openldap:
    driver: local

services:
  redis:
    restart: always
    image: sameersbn/redis:latest
    command:
      - --loglevel warning
    volumes:
      - redis:/var/lib/redis


  postgresql:
    restart: always
    image: sameersbn/postgresql:9.6-2
    environment:
      - DB_USER=usr1234132
      - DB_PASS=mj2jir1ih
      - DB_NAME=redmine,gitlab
    volumes:
      - postgresql:/var/lib/postgresql

  redmine:
    restart: always
    image: sameersbn/redmine:3.3.2-1
    environment:
      - TZ=America/Bogota

      - DB_HOST=postgresql
      - DB_USER=usr1234132
      - DB_PASS=mj2jir1ih
      - DB_NAME=redmine

      - REDMINE_HTTPS=true
      - REDMINE_SECRET_TOKEN=jk1usfkj19sfn1r094tkl56ags

      - REDMINE_CONCURRENT_UPLOADS=2

      - REDMINE_BACKUP_SCHEDULE=daily
      - REDMINE_BACKUP_EXPIRY=604800

      - SMTP_HOST=mail.privateemail.com
      - SMTP_USER=system@mllcrtv.me
      - SMTP_PASS=mllcrtvsystem
    volumes:
      - redmine:/home/redmine/data

  gitlab:
    restart: always
    image: sameersbn/gitlab:9.0.5
    environment:
      - DB_HOST=postgresql
      - DB_USER=usr1234132
      - DB_PASS=mj2jir1ih
      - DB_NAME=gitlab

      - TZ=America/Bogota
      - GITLAB_TIMEZONE=Bogota

      - GITLAB_HTTPS=true

      - GITLAB_HOST=git.mllcrtv.me
      - GITLAB_PORT=443
      - GITLAB_SSH_PORT=10022
      - GITLAB_SECRETS_DB_KEY_BASE=jd92kg92mdgi2emrdwgi2ermdi2efmwdi2efjdwfi2ef
      - GITLAB_SECRETS_SECRET_KEY_BASE=mfdi2efifi2efi2gwd92efmf9dwi2efidf92efm9
      - GITLAB_SECRETS_OTP_KEY_BASE=sfi12wfdfmg9j9hhuyhsd2efinu8dnf280j307234ni

      - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true

      - GITLAB_EMAIL=system@mllcrtv.me
      - GITLAB_EMAIL_REPLY_TO=system@mllcrtv.me
      - GITLAB_INCOMING_EMAIL_ADDRESS=system@mllcrtv.me

      - GITLAB_BACKUP_SCHEDULE=daily
      - GITLAB_BACKUP_EXPIRY=604800

      - SMTP_HOST=mail.privateemail.com
      - SMTP_USER=system@mllcrtv.me
      - SMTP_PASS=mllcrtvsystem

      - IMAP_ENABLED=true
      - IMAP_HOST=mail.privateemail.com
    ports:
      - "10022:22"
    volumes:
      - gitlab:/home/git/data

  nginx:
    restart: always
    image: sameersbn/nginx:1.10.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./certs:/certs

  openldap:
    restart: always
    image: osixia/openldap:1.1.8
    command: --copy-service
    environment:
      - LDAP_ORGANISATION=Malla Creativa
      - LDAP_DOMAIN=ldaps.mllcrtv.me
      - LDAP_ADMIN_PASSWORD=jr82kdf2kr
      - LDAP_TLS=true
      - LDAP_TLS_CRT_FILENAME=cert.pem
      - LDAP_TLS_CA_CRT_FILENAME=chain.pem
      - LDAP_TLS_KEY_FILENAME=privkey.pem
      - LDAP_TLS_ENFORCE=true
    ports:
      - "389:389"
      - "636:636"
    hostname: "ldaps.mllcrtv.me"
    volumes:
      - openldap:/var/lib/ldap
      - ./certs:/container/service/slapd/assets/certs/

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=true
