version: '2'


volumes:
  redis:
    driver: local

  postgresql:
    driver: local

  redmine:
    driver: local

  gitlab:
    driver: local

services:
  redis:
    restart: always
    image: sameersbn/redis:latest
    command:
      - --loglevel warning
    volumes:
      - redis:/var/lib/redis


  postgresql:
    restart: always
    image: sameersbn/postgresql:9.6-2
    environment:
      - DB_USER=rdmn
      - DB_PASS=dIa84!j.g
      - DB_NAME=redmine
    volumes:
      - postgresql:/var/lib/postgresql

  redmine:
    restart: always
    image: sameersbn/redmine:3.3.2-1
    environment:
    - TZ=America/Bogota

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=rdmn
    - DB_PASS=dIa84!j.g
    - DB_NAME=redmine

    - REDMINE_PORT=5555
    - REDMINE_HTTPS=true
    - REDMINE_SECRET_TOKEN=jk1usfkj19sfn1r094tkl56ags

    - REDMINE_CONCURRENT_UPLOADS=2

    - REDMINE_BACKUP_SCHEDULE=daily
    - REDMINE_BACKUP_EXPIRY=604800

    - SMTP_HOST=mail.privateemail.com
    - SMTP_USER=system@mllcrtv.me
    - SMTP_PASS=mllcrtvsystem

    - IMAP_ENABLED=true
    - IMAP_HOST=mail.privateemail.com

    - SSL_CERTIFICATE_PATH=/certs/cert.pem
    - SSL_KEY_PATH=/certs/privkey.pem
    - SSL_DHPARAM_PATH=/certs/dhparam.pem

    ports:
    - "5555:80"
    volumes:
    - redmine:/home/redmine/data
    - ./certs:/certs
