version: '2'

volumes:
  redis:
    driver: local

  postgresql:
    driver: local

  redmine:
    driver: local

  gitea:
    driver: local

services:
  redis:
    restart: always
    image: sameersbn/redis:latest
    volumes:
      - redis:/var/lib/redis

  postgresql:
    restart: always
    image: sameersbn/postgresql:9.6-2
    environment:
      - PG_PASSWORD=mj2jir1ih
      - DB_NAME=redmine,gitea
    volumes:
      - postgresql:/var/lib/postgresql

  redmine:
    restart: always
    image: sameersbn/redmine:3.3.2-1
    environment:
      - TZ=America/Bogota

      - DB_ADAPTER=postgresql
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=mj2jir1ih
      - DB_NAME=redmine

      - REDMINE_HTTPS=true
      - REDMINE_SECRET_TOKEN=jk1usfkj19sfn1r094tkl56ags

      - REDMINE_CONCURRENT_UPLOADS=2

      - REDMINE_BACKUP_SCHEDULE=daily
      - REDMINE_BACKUP_EXPIRY=604800

      - SMTP_HOST=mail.privateemail.com
      - SMTP_USER=system@mllcrtv.me
      - SMTP_PASS=mllcrtvsystem
    volumes:
      - redmine:/home/redmine/data

  gitea:
    restart: always
    image: gitea/gitea:latest
    environment:
      - GITEA_CUSTOM=/custom
    ports:
      - "10022:22"
    volumes:
      - gitea:/data
      - ./gitea/conf/app.ini:/custom/conf/app.ini

  nginx:
    restart: always
    image: sameersbn/nginx:1.10.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./certs:/certs
